#!/usr/bin/env bash

if [ $# -lt 1 ];then
	echo "Usage: $0 <username>"
	exit 1
fi

USERNAME=$1

docker exec -ti freeradius useradd -d /home/$USERNAME -m $USERNAME
docker exec -ti freeradius passwd $USERNAME
docker exec -ti freeradius su -c "google-authenticator -t" -l $USERNAME
